### ISSUE TITLE
Where is cat?

### ISSUE THREAD

**Issue by mattsp1290** [animate-object/cat-viewer#22]
I would like to view one cat please.

**Comment by mattsp1290** [comment]
Please. Just a single cat for viewing.

**Comment by animate-object** [comment]
I'm sorry, progress on this project was halted after I received a number of strongly worded cease and desist letters.

At the advise of my lawyer, I have decided to discontinue this effort. Our vision was to democratize cat - to put into the hands of the many what has for so long been controlled by the few.

Simply put, big cat won't allow it.

**Comment by mattsp1290** [comment]
Closing this issue with great sadness as Big Cat tries to take away one of my last remaining hopes for this world.
